# Generated by Django 5.1.1 on 2024-09-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
        migrations.AddField(
            model_name='trade',
            name='buy_sell',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', help_text='Buy or Sell order', max_length=1),
        ),
        migrations.AddField(
            model_name='trade',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Capital allocated to this trade', max_digits=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price at which trade is entered', max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='expiry',
            field=models.CharField(choices=[('current_week', 'Current Week'), ('next_week', 'Next Week'), ('monthly', 'Monthly')], default='current_week', help_text='Expiry period of the options/futures', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='name',
            field=models.CharField(default='', help_text='Name of the trade', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='segment',
            field=models.CharField(choices=[('EQ', 'Equity'), ('FO', 'Futures & Options'), ('CD', 'Currency Derivatives'), ('CO', 'Commodity Derivatives')], default='EQ', help_text='Trading segment', max_length=2),
        ),
        migrations.AddField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stop loss price to limit risk', max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='target_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Target price to exit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(help_text='Number of lots or shares'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(help_text='Trading symbol, e.g., NIFTY50', max_length=10),
        ),
    ]
