# Generated by Django 5.1.1 on 2024-09-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_trade_action_userfollower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='action',
        ),
        migrations.DeleteModel(
            name='UserFollower',
        ),
    ]
