# Generated by Django 5.1.1 on 2024-10-10 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_remove_trade_action_delete_userfollower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('master_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_traders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZerodhaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zerodha_user_id', models.CharField(max_length=50)),
                ('zerodha_password', models.CharField(max_length=100)),
                ('totp_secret', models.CharField(max_length=32)),
                ('enctoken', models.TextField(blank=True, null=True)),
                ('last_token_update', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'zerodha_user_id')},
            },
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
